VocusGroup.site/Models/Generated/SharePricePage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VocusGroup.site.Models.Generated.PublishedContentModels
{
    public partial class SharePricePage
    {
        public string Title { get; set; }
        public string ExchangeOne { get; set; }

        public string ExchangeTwo { get; set; }

        public string  Price { get; set; }

        public string ChangePercent { get; set; }

        public string Volume { get; set; }

        public string TodaysOpen { get; set; }

        public string PreviousClose { get; set; }

        public string Bid { get; set; }

        public string Ask { get; set; }

        public string IntradayHigh { get; set; }

        public string IntradayLow { get; set; }

        public string FiftyTwoWeekHigh { get; set; }

        public string FiftyTwoWeekLow { get; set; }

        public string DataAsOf { get; set; }

        public string Change { get; set; }

        public string CurrencyType { get; set; }
    }
}

VocusGroup.site/Controllers/SharePricePageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;
using VocusGroup.site.Models.Generated.PublishedContentModels;

namespace VocusGroup.site.Controllers
{
    public class SharePricePageController : RenderMvcController
    {

        [HttpGet]
        public override ActionResult Index(RenderModel model)
        {
            SharePricePage viewModel = new SharePricePage(model.Content);
            HttpWebRequest request
             = WebRequest.Create(Helper.WebHelper.GetConfiguration(ApplicationConstants.ApplicationConstants.KeysharePriceUrl)) as HttpWebRequest;

            //  Get response
            using (HttpWebResponse response = request.GetResponse() as HttpWebResponse)
            {
                //  Load data into a dataset
                DataSet dsParsedData = new DataSet();
                dsParsedData.ReadXml(response.GetResponseStream());
                if (dsParsedData.Tables.Contains("Stock_Quote"))
                {
                    var changePercent = 0.00;
                    viewModel.Title = dsParsedData.Tables[2].Rows[0][23].ToString();
                    viewModel.ExchangeOne = dsParsedData.Tables[2].Rows[0][24].ToString();
                    viewModel.ExchangeTwo=dsParsedData.Tables[2].Rows[0][25].ToString();
                    viewModel.Price = dsParsedData.Tables[2].Rows[0][1].ToString();

                  
                    viewModel.Volume = dsParsedData.Tables[2].Rows[0][9].ToString();
                    viewModel.TodaysOpen = dsParsedData.Tables[2].Rows[0][10].ToString();
                    viewModel.PreviousClose = dsParsedData.Tables[2].Rows[0][11].ToString();
                    viewModel.Change = dsParsedData.Tables[2].Rows[0][2].ToString();
                    var prevClose = Convert.ToDouble(viewModel.PreviousClose);
                    if (prevClose != 0.00)
                    {
                         changePercent = (Convert.ToDouble(viewModel.Change) / Convert.ToDouble(viewModel.PreviousClose)) * 100;
                    }
                    viewModel.ChangePercent = Math.Round(changePercent,2).ToString()+'%';
                    viewModel.Bid = (dsParsedData.Tables[2].Rows[0][3].ToString());
                    viewModel.Ask = (dsParsedData.Tables[2].Rows[0][4].ToString());
                    viewModel.IntradayHigh = (dsParsedData.Tables[2].Rows[0][7].ToString());
                    viewModel.IntradayLow = (dsParsedData.Tables[2].Rows[0][8].ToString());
                    viewModel.FiftyTwoWeekHigh = (dsParsedData.Tables[2].Rows[0][12]).ToString();
                    viewModel.FiftyTwoWeekLow = (dsParsedData.Tables[2].Rows[0][13]).ToString();
                    viewModel.CurrencyType= (dsParsedData.Tables[2].Rows[0][26]).ToString();
                    DateTime date = Convert.ToDateTime(dsParsedData.Tables[3].Rows[0][2]);
                    viewModel.DataAsOf = String.Format("{0:dd.MM.yyyy h.mmtt ET}", date);
                }
                else
                {
                    viewModel.ExchangeOne = "Error in extracting data.";
                }


            }

            return CurrentTemplate(viewModel);
        }

    }
}

VocusGroup.site/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactPage>
@using ContentModels = VocusGroup.site.Models.Generated.PublishedContentModels;
@{
    Layout = "MasterLayout.cshtml";
    var home = Model.Content.AncestorOrSelf<Home>(1);
    var brandItem = home.Children<ContentModels.OurBrands>().FirstOrDefault();
}
<main class="main main-cntr">
    <div class="container">
        <div class="row">
            <div class="page-top-cntr">
                <h1 class="page__title vocus_blue">Contact</h1>
                <div class="page__breadcrumb">
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li class="active"><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
            <!-- /.page-top-cntr -->
            <section class="page-content-cntr contact-main-cntr clearfix">
                <div class="investor-main-content contact-main-content">
                    <div class="contact-top">
                        <div class="contact-enquiry clearfix">
                            <div class="col-md-3">
                                <h3 class="sub-title__big enquiry-title">General Enquiries</h3>
                            </div>
                            <div class="col-md-9">
                                @Model.Content.Content

                            </div>
                        </div>
                    </div>
                    <div class="contact-bottom">
                        <div class="clearfix thumbnail-section">
                            <div class="col-md-3 compliment-title">
                                <h3 class="sub-title__big enquiry-title">COMPLIMENT OR COMPLAIN</h3>
                            </div>
                            <div class="col-md-9 contact-thumbnails">
                                <div class="contact-thumb-list-cntr">
                                    @if (brandItem.Children<ContentModels.BrandItems>().Any())
                                    {
                                        foreach (var item in brandItem.Children<ContentModels.BrandItems>())
                                        {
                                            <div class="contact-item">
                                                <a href="@item.BrandUrl" target="_blank" title="@item.Name" class="brand-skyblue" style="background-color:#@item.BackgroundColour">
                                                    @if (!string.IsNullOrEmpty(item.BrandImage))
                                                    {
                                                        <img src="@Umbraco.Media(item.BrandImage).Url" alt="@item.Name" />
                                                    }
                                                </a>
                                                <div class="contact-summary">
                                                    <a href="@item.BrandUrl" target="_blank" class="info-arrow" title="@item.Name">
                                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1304 1304" fill="#84d0ed"><g><path d="M0 587h1238.5v130H0z"></path><path d="M1209.167 745.167L557.977 89.365 651 .5l653 651.333"></path><path d="M1304 651.833L652.5 1304.5 560 1212l648.5-655"></path></g></svg>
                                                        <span>contact @item.Name</span>
                                                    </a>
                                                </div>

                                            </div>
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.privacy-main-content -->
            </section>
            <!-- /.page-content-cntr -->
        </div>      
    </div>
</main>

VocusGroup.site/Views/FullPageContentLayout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "MasterLayout.cshtml";
}

VocusGroup.site/Views/LeftMenuPageLayout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "MasterLayout.cshtml";
    var parentPage = (dynamic)CurrentPage.Parent;
}
<main class="main main-cntr">
    <div class="container">
        <div class="row">
            <section class="page-top-cntr">
                <h1 class="page__title vocus_blue">@CurrentPage.Name</h1>
                @{ Html.RenderPartial("BreadcrumbNavigation"); }
                <!-- /.page__breadcrumb -->
            </section>
            <!-- /.page-top-cntr -->
            <section class="page-content-cntr clearfix">
                <div class="col-sm-3 page-left-navigation">
                    <div class="left__nav-cntr">
                        <h3 class="small-title vocus_blue">About us</h3>
                        <ul>
                            @foreach (var childPage in parentPage.Children.Where("showInLeftMenu"))
                            {
                                if ((int)CurrentPage.Id == (int)childPage.Id)
                                {
                                    <li class="active">
                                        <a href="@childPage.Url">@childPage.Name</a>
                                    </li>
                                }
                                else
                                {
                                    <li>
                                        <a href="@childPage.Url">@childPage.Name</a>
                                    </li>
                                }
                            }
                        </ul>
                    </div>
                </div>
                <!-- /.page-left-navigation -->
                <div class="col-sm-9 page-right-content about-inner-main-cntr">
                    @RenderBody()
                    </div>
              </section>
            <!-- /.page-content-cntr -->
        </div>
    </div>
</main>
<!-- /.main -->

VocusGroup.site/Views/SharePricePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.SharePricePage>
@using ContentModels = VocusGroup.site.Models.Generated.PublishedContentModels;
@{
    Layout = "LeftMenuPageLayout.cshtml";
    var parentPage = Model.Content.Parent;
    var content = Umbraco.Content(CurrentPage.Id);
}


<div class="page__main-content">
    <div class="main__content-cntr clearfix">
        <div class="content__left">
            <div class="main-content">
                <div class="share-price-main-cntr">
                    <h2 class="sub-title maximum_blue_green">@Model.Content.Title</h2>
                    @if (Model.Content.ExchangeOne != "Error in extracting data.")
                    {
                       
                        <div class="price__list-cntr">
                            <ul class="price__items-list">
                                <li class="price__item">
                                    <span class="price__title">
                                        Exchange
                                    </span>
                                    <span class="price__amount">
                                        @Model.Content.ExchangeOne ( @Model.Content.ExchangeTwo)
                                    </span>
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        Price
                                    </span>
                                    <span class="price__amount">
                                        @Model.Content.CurrencyType@Model.Content.Price
                                    </span>
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        Change (%)
                                    </span>
                                    @if (Model.Content.Change.Contains("-"))
                                    {
                                <span class="price__amount change-price-cntr price-down">
                                    <span class="triangle-down"></span>
                                    @Model.Content.Change (@Model.Content.ChangePercent)
                                </span>
                                    }
                                    else
                                    {
                                <span class="price__amount change-price-cntr price-up">
                                    <span class="triangle-up"></span>
                                    @Model.Content.Change (@Model.Content.ChangePercent)
                                </span>
                                    }
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        Volume
                                    </span>
                                    <span class="price__amount pricevolume">
                                        @Model.Content.Volume
                                    </span>
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        Today's Open
                                    </span>
                                    <span class="price__amount">
                                        @Model.Content.CurrencyType@Model.Content.TodaysOpen
                                    </span>
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        Previous Close
                                    </span>
                                    <span class="price__amount">
                                        @Model.Content.CurrencyType@Model.Content.PreviousClose
                                    </span>
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        Bid
                                    </span>
                                    <span class="price__amount">
                                        @Model.Content.CurrencyType@Model.Content.Bid
                                    </span>
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        Ask
                                    </span>
                                    <span class="price__amount">
                                        @Model.Content.CurrencyType@Model.Content.Ask
                                    </span>
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        Intraday High
                                    </span>
                                    <span class="price__amount">
                                        @Model.Content.CurrencyType@Model.Content.IntradayHigh
                                    </span>
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        Intraday Low
                                    </span>
                                    <span class="price__amount">
                                        @Model.Content.CurrencyType@Model.Content.IntradayLow
                                    </span>
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        52 Week High
                                    </span>
                                    <span class="price__amount">
                                        A$@Model.Content.FiftyTwoWeekHigh
                                    </span>
                                </li>
                                <li class="price__item">
                                    <span class="price__title">
                                        52 Week Low
                                    </span>
                                    <span class="price__amount">
                                        @Model.Content.CurrencyType@Model.Content.FiftyTwoWeekLow
                                    </span>
                                </li>
                            </ul>
                            <div class="data-info-cntr">
                                <span>Data as of @Model.Content.DataAsOf</span>
                                <span>Minimum 15 minutes delay</span>
                                <span>@Html.ActionLink("Refresh quote", "Index", "SharePricePage",new { @style= "color:#57585a" })</span>
                            </div>
                        </div>
                    }
                    else
                    {
                        <h2 class="sub-title maximum_blue_green">VOC.AX</h2>
                        <div class="share-detail-cntr">
                            <div class="share__note-info">
                                <span>Please try again later. The data is not available from server.</span>
                            </div>
                        </div>
                    }
                    <!-- /.price__list-cntr -->
                        <div class="nasdaq-chart-cntr">
                            <div class="chart-detail" >
                                <iframe style="width:100%;height:100%" src="http://api.nasdaqomx.wallst.com/AdvancedChart?symbol=VOC.AX-Vocus"> </iframe>
                            </div>
                            <span>Data provided by Nasdaq. Minimum 15 minutes delayed</span>
                        </div>
                    <!-- nasdaq-chart-cntr -->
                                </div>
                            </div>
                        </div>
        <!-- /.content__left -->
                        <div class="content__right">
                            @if (Model.Content.RelatedContent != null)
                            {

                                <div class="related-content-cntr">
                                    <h3 class="small-title maximum_blue_green">Related content</h3>
                                    <div class="related__links">
                                        <ul>
                                            @foreach (var link in Model.Content.RelatedContent.ToObject<List<dynamic>>())
                                            {
                                                <li>
                                                    <a class="vocus-btn maximum_blue_green_bg btn__related-content" href="@link.link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1304 1304" fill="#fff"><g><path d="M0 587h1238.5v130H0z"></path><path d="M1209.167 745.167L557.977 89.365 651 .5l653 651.333"></path><path d="M1304 651.833L652.5 1304.5 560 1212l648.5-655"></path></g></svg> <span>@link.caption</span></a>
                                                </li>
                                            }
                                        </ul>
                                    </div>
                                </div>
                            }
                            <!-- /.related-content-cntr -->
                        </div>
        <!-- /.content__right -->
                                </div>
                            </div>

VocusGroup.site/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.TextPage>
@using ContentModels = VocusGroup.site.Models.Generated.PublishedContentModels;
@{
    Layout = "MasterLayout.cshtml";
}

<main class="main main-cntr">
    <div class="container">
        <div class="row">
            <section class="page-top-cntr">
                <h1 class="page__title vocus_blue">@Model.Content.Name</h1>
                @{ Html.RenderPartial("BreadcrumbNavigation"); }
                <!-- /.page__breadcrumb -->
            </section>
            <!-- /.page-top-cntr -->
            <section class="page-content-cntr privacy-statement-cntr clearfix">
                <div class="investor-main-content privacy-main-content">
                    <h2 class="sub-title__big">Privacy Statement</h2>
                    <div class="privacy-content">
                        <p>
                            @Html.Raw(@Model.Content.BodyContent)
                        </p>
                    </div>
                </div>
                <!-- /.privacy-main-content -->
            </section>
            <!-- /.page-content-cntr -->
        </div>
    </div>
</main>
<!-- /.main -->